### ISSUE TITLE
DATABASE_URL and DISCORD_TOKEN Setup

### ISSUE THREAD

**Issue by dirtdagg** [chenyejia/discord_turnip_bot#3]
Hello,
I am looking to set this up in my own server but am having a hard time getting it setup. I believe the "DISCORD_TOKEN" portion is the bots token which I figured out. 
I can't seem to figure out what to put in place of of "DATABASE_URL" in bot.py

`DATABASE_URL = os.environ["DATABASE_URL"]`

What do I put in place of DATABASE_URL? Is it Discord related or do I need to setup some database externally that this writes to?

As a followup, is there a list of commands the bot responds to?
Thanks for the help!

**Comment by chenyejia** [comment]
Hi! If you just want to use the bot, I could send you a link to invite it to your server (though it's still pretty rough).

If you're interested in hosting your own version, I'm using Heroku to host, and using their postgresql add-on for the database (which is what the `DATABASE_URL` refers to). There's some scripts to set up the tables which I have not added to the repo.

The current commands available are:
```
  add_price  Add price data. ex: /t add 4/1/2020 am 100
  bug        Show price for bug.
  fish       Show price for fish.
  help       Shows this message
  hot        Show crafting and price information for hot items.
  patterns   List turnip price patterns.
  ping       pong
  remove_me  Remove all data about your prices
  show_graph Show graph of turnip prices for this week
```

(available through the `help` command)

**Comment by dirtdagg** [comment]
Thank you, that is super helpful! I ended up getting another bot running that I am trying out right now locally on my machine, which was my goal. Good work on this!
